services:
    # PostgreSQL
    postgres:
        container_name: postgres_luna
        image: postgres:16
        restart: on-failure
        environment:
            POSTGRES_USER: system
            POSTGRES_PASSWORD: system
            POSTGRES_MULTIPLE_DATABASES: "luna_database, luna_users, luna_auth, luna_workspaces, luna_files, luna_activity, luna_templates, luna_tags, luna_graphs"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./postgres/init:/docker-entrypoint-initdb.d # Скрипты для инициализации
        ports:
            - "15432:5432"
        networks:
            - backend

    # MongoDB
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: system
            MONGO_INITDB_ROOT_PASSWORD: system
        volumes:
            - mongodb_data:/data/db
            - ./mongodb/init:/docker-entrypoint-initdb.d # Скрипты для инициализации
        ports:
            - "27017:27017"
        networks:
            - backend

    # RabbitMQ
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        restart: on-failure
        environment:
            RABBITMQ_DEFAULT_USER: system
            RABBITMQ_DEFAULT_PASS: system
        ports:
            - "5672:5672"   # AMQP порт
            - "15672:15672" # Management UI
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - backend

    # Redis
    redis:
        image: redis:alpine
        container_name: redis
        restart: always
        command: redis-server --requirepass system
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - backend

    # Services
    luna.auth.api:
        image: luna.auth.api
        ports:
            - "7000:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        build:
            context: .
            dockerfile: Luna.Auth.API/Dockerfile
        networks:
            - backend
        env_file:
            - "Luna.Auth.API/.env.local"


    luna.workspaces.api:
        image: luna.workspaces.api
        ports:
            - "7003:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        build:
            context: .
            dockerfile: Luna.Workspaces.API/Dockerfile
        networks:
            - backend


    luna.users.api:
        image: luna.users.api
        ports:
            - "7001:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        build:
            context: .
            dockerfile: Luna.Users.API/Dockerfile
        networks:
            - backend

    luna.pages.api:
        image: luna.pages.api
        ports:
            - "7005:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        build:
            context: .
            dockerfile: Luna.Pages.API/Dockerfile
        networks:
            - backend

    luna.users.gRPC:
        image: luna.auth.grpc
        ports:
            - "7002:8080"
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        build:
            context: .
            dockerfile: Luna.Users.gRPC/Dockerfile
        networks:
            - backend

    luna.gateway.api:
        image: luna.gateway.api
        container_name: luna_gateway
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        ports:
            - "8000:8080"
        build:
            context: .
            dockerfile: Luna.Gateway.API/Dockerfile
        networks:
            - backend
        depends_on:
            - luna.auth.api

    luna.notification.api:
        image: luna.notification.api
        container_name: luna_notification
        environment:
            ASPNETCORE_ENVIRONMENT: Release
        ports:
            - "7004:8080"
        build:
            context: .
            dockerfile: Luna.Notification.API/Dockerfile
        networks:
            - backend
        depends_on:
            - rabbitmq
        restart: on-failure

networks:
    backend:
        driver: bridge

volumes:
    postgres_data:
        driver: local
    mongodb_data:
        driver: local
    rabbitmq_data:
        driver: local
    redis_data:
        driver: local

