services:

  luna.gateway.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.gateway.api
    ports:
      - "7000:8080"
    build:
      context: .
      dockerfile: Luna.Gateway.API/Dockerfile

  luna.auth.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.auth.api
    ports:
      - "7001:8080"
    build:
      context: .
      dockerfile: Luna.Auth.API/Dockerfile

  luna.users.grpc:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.users.grpc
    ports:
      - "7002:8080"
    build:
      context: .
      dockerfile: Luna.Users.Grpc/Dockerfile

  luna.users.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.users.api
    ports:
      - "7003:8080"
    build:
      context: .
      dockerfile: Luna.Users.API/Dockerfile

  luna.workspace.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.workspace.api
    ports:
      - "7004:8080"
    build:
      context: .
      dockerfile: Luna.Workspace.API/Dockerfile

  luna.data.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.data.api
    ports:
      - "7005:8080"
    build:
      context: .
      dockerfile: Luna.Data.API/Dockerfile

  luna.tasks.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.tasks.api
    ports:
      - "7006:8080"
    build:
      context: .
      dockerfile: Luna.Tasks.API/Dockerfile

  luna.notification.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Release
    image: luna.notification.api
    ports:
      - "7007:8080"
    build:
      context: .
      dockerfile: Luna.Notification.API/Dockerfile
